DROP TABLE IF EXISTS `iotaskdetails`;
CREATE TABLE `iotaskdetails` (
    `IoTaskDetailId` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `IoTaskId` int(10) unsigned NOT NULL,
    `Par1` varchar(50) COLLATE utf8_bin DEFAULT NULL,
    `Par2` varchar(100) COLLATE utf8_bin DEFAULT NULL,
    `par3` varchar(1000) COLLATE utf8_bin DEFAULT NULL,
    `Par4` varchar(150) COLLATE utf8_bin DEFAULT NULL,
    `par5` varchar(50) COLLATE utf8_bin DEFAULT NULL,
    `par6` varchar(500) COLLATE utf8_bin DEFAULT NULL,
    `TaskDetailOrder` int(11) DEFAULT '0',
    `Info` varchar(100) COLLATE utf8_bin DEFAULT NULL,
    PRIMARY KEY (`IoTaskDetailId`)
) ENGINE=InnoDB AUTO_INCREMENT=78 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

LOCK TABLES `iotaskdetails` WRITE;
/*!40000 ALTER TABLE `iotaskdetails` DISABLE KEYS */;
INSERT INTO `iotaskdetails` VALUES
('1','1','transactions','TransactionId','DateAndTime<''{dayBeforeStr}''','Archived','copy',NULL,'1',NULL),
('2','1','transactiondetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'12',NULL),
('3','1','transactiondetailslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'11',NULL),
('4','1','transactionslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'13',NULL),
('5','1','leaktestermeasurementsdetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'3',NULL),
('6','1','leaktestermeasurementsdetailslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'2',NULL),
('7','1','leaktestermeasurements','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'5',NULL),
('8','1','leaktestermeasurementslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'4',NULL),
('9','1','heliummeasurement','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'7',NULL),
('10','1','heliummeasuredpoints','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'6',NULL),
('11','1','forcepath','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'10',NULL),
('12','1','forcepathdetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'8',NULL),
('13','1','forcepathwindows','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'9',NULL),
('14','2','transactions','TransactionId','','Archived','delete',NULL,'1',NULL),
('15','2','transactiondetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'12',NULL),
('16','2','transactiondetailslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'11',NULL),
('17','2','transactionslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'13',NULL),
('18','2','leaktestermeasurementsdetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'3',NULL),
('19','2','leaktestermeasurementsdetailslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'2',NULL),
('20','2','LeaktesterMeasurements','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'5',NULL),
('21','2','LeaktesterMeasurementslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'4',NULL),
('22','2','heliummeasurement','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'7',NULL),
('23','2','heliummeasuredpoints','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'6',NULL),
('24','2','forcepath','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'10',NULL),
('25','2','forcepathdetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'8',NULL),
('26','2','forcepathwindows','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'9',NULL),
('27','3','transactions_exp','DateAndTime DESC','TransactionId >= 226671 AND TransactionId <= 226721','transactiondetailsprogramresults_exp;ProgramName;ProgramId;ResultProgram;TransactionId;get','get','Measurements;"ID";Time;ResultDescription;ResultValue;DmcGenerator;DmcCustomer;Counter;"Etalon";MSA;qualityCode;ItemId;ItemName;EmployeeId;OrderId;"PLC"','1',NULL),
('28','3','transactiondetails_exp','TransactionId DESC, ProgramId',NULL,NULL,'get','Details;"ID";OperationId;OperationName;ProgramId;ProgramName;Time;ResultDescription;ResultValue;MachineStation;MachineSubStation;ErrorId;MeasurementNumber;MeasurementType;Note;"MES";"Etalon"','2',NULL),
('29','3','transactionprograms_exp','DateAndTime DESC',NULL,'transactiondetailsprogramresults_exp;ProgramIdAndName;ProgramId;ResultProgramExtended;TransactionId','get','Programs;"ID";Time;DmcGenerator;DmcCustomer;ItemId;ItemName;qualityCode;"PLC";ResultDescription;ResultDescription;"Etalon"','3',NULL),
('30','3','transactionslog_exp','DateAndTime DESC',NULL,NULL,'none','Versions;"ID";Version;Time;ResultDescription;ResultValue;DmcGenerator;DmcCustomer;Counter;"Etalon";qualityCode;ItemId;ItemName;EmployeeId;OrderId;"PLC"','4',NULL),
('31','3','transactiondetailslog_exp','TransactionId DESC, ProgramId',NULL,NULL,'none','VersionDetails;"ID";Version;OperationId;OperationName;ProgramId;ProgramName;Time;ResultDescription;ResultValue;MachineStation;MachineSubStation;ErrorId;MeasurementNumber;MeasurementType;Note;"MES";"Etalon"','5',NULL),
('32','3','leaktestermeasurements_exp','MeasurementNumber DESC',NULL,NULL,'get','LeakTester;"ID";Time;ResultDescription;DmcGenerator;Leak{"ml/min"};"Δp";Thread;ErrorId;ProgramId;ItemName;MeasurementNumber;DetailsArg{"ID"};"Etalon"','6',NULL),
('33','3','leaktestermeasdetails_exp','TransactionId DESC, RecordedTime',NULL,'','get','LeakTesterArg{Pos};"ID";Phase;Time;Sensor1;Sensor2;OutputPressure;ResultDescription;"Etalon"','7',NULL),
('34','3','heliummeasurement_exp','TransactionId DESC, TransactionVer',NULL,NULL,'get','Helium;"ID";Version;MeasurementNumber;Program;Leak{"ml/min"};ResultDescription;LeakMax{"ml/min"};LeakAvg{"ml/min"};LeakMin{"ml/min"};LeakLastPoint{"ml/min"};ScrapArgs{"+","ml/min"};ScrapArgs{"-","ml/min"};Time;"Etalon"','8',NULL),
('35','3','heliummeasuredpoints_exp','TransactionId DESC, TransactionVer DESC, Pos',NULL,'','get','HeluimPoints;"ID";Version;Point;Phase;Leak{"ml/min"};PressurePart{"ml/min"};ChamberPressure{"ml/min"};AbsolutePreasureChamber{"ml/min"};VacuumPreasureChamber{"ml/min"};Time;Time;"Etalon"','9',NULL),
('36','3','forcepath_exp','TransactionId DESC, TransactionDetailsId DESC',NULL,'transactiondetailsforcepathwindows_exp;AreaForceMinMax;AreaForceMinMax;ForceMinMax;TransactionId','get','ForcePath;"ID";Time;ResultDescription;ProgramId;ProgramName;DmcGenerator;DetailsArg{"ID"}','10',NULL),
('37','3','forcepathdetails_exp','TransactionId DESC, TransactionDetailsId DESC, PointNum',NULL,'','get','ForcePathArg{Pos};"ID";Point;Force;Path;Time;DetailsArg{"ID"};Time;"Etalon"','11',NULL),
('38','4','transactions','TransactionId','DateAndTime<''{dayBeforeStr}''','Archived','copy',NULL,'1',NULL),
('39','4','transactiondetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'12',NULL),
('40','4','transactiondetailslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'11',NULL),
('41','4','transactionslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'13',NULL),
('42','4','leaktestermeasurementsdetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'3',NULL),
('43','4','leaktestermeasurementsdetailslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'2',NULL),
('44','4','leaktestermeasurements','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'5',NULL),
('45','4','leaktestermeasurementslog','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'4',NULL),
('46','4','heliummeasurement','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'7',NULL),
('47','4','heliummeasuredpoints','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'6',NULL),
('48','4','forcepath','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'10',NULL),
('49','4','forcepathdetails','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'8',NULL),
('50','4','forcepathwindows','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'9',NULL),
('51','5','transactions_exp','DateAndTime DESC','DateAndTime >= CURDATE() - INTERVAL 1 DAY AND DateAndTime < CURDATE()','transactiondetailsprogramresults_exp;ProgramName;ProgramId;ResultProgram;TransactionId','get','Measurements;"ID";Time;ResultDescription;ResultValue;DmcGenerator;DmcCustomer;Counter;"Etalon";MSA;qualityCode;ItemId;ItemName;EmployeeId;OrderId;"PLC"','1',NULL),
('52','5','transactiondetails_exp','DateAndTime DESC, ProgramId',NULL,NULL,'get','Details;"ID";OperationId;OperationName;ProgramId;ProgramName;Time;ResultDescription;ResultValue;MachineStation;MachineSubStation;ErrorId;MeasurementNumber;MeasurementType;Note;"MES";"Etalon"','2',NULL),
('53','5','transactionprograms_exp','DateAndTime DESC',NULL,'transactiondetailsprogramresults_exp;ProgramIdAndName;ProgramId;ResultProgramExtended;TransactionId','get','Programs;"ID";Time;DmcGenerator;DmcCustomer;ItemId;ItemName;qualityCode;"PLC";ResultDescription;ResultDescription;"Etalon"','3',NULL),
('54','5','transactionslog_exp','DateAndTime DESC',NULL,NULL,'get','Versions;"ID";Version;Time;ResultDescription;ResultValue;DmcGenerator;DmcCustomer;Counter;"Etalon";qualityCode;ItemId;ItemName;EmployeeId;OrderId;"PLC"','4',NULL),
('55','5','transactiondetailslog_exp','DateAndTime DESC, ProgramId',NULL,NULL,'get','VersionDetails;"ID";Version;OperationId;OperationName;ProgramId;ProgramName;Time;ResultDescription;ResultValue;MachineStation;MachineSubStation;ErrorId;MeasurementNumber;MeasurementType;Note;"MES";"Etalon"','5',NULL),
('56','5','leaktestermeasurements_exp','DateAndTime DESC',NULL,NULL,'get','LeakTester;"ID";Time;ResultDescription;DmcGenerator;Leak{"ml/min"};"Δp";Thread;ErrorId;ProgramId;ItemName;MeasurementNumber;DetailsArg{"ID"};"Etalon"','6',NULL),
('57','5','leaktestermeasdetails_exp','DateAndTime DESC, RecordedTime',NULL,'','get','LeakTesterArg{Pos};"ID";Phase;Time;Sensor1;Sensor2;OutputPressure;ResultDescription;"Etalon"','7',NULL),
('58','5','heliummeasurement_exp','DateAndTime DESC, TransactionVer',NULL,NULL,'get','Helium;"ID";Version;MeasurementNumber;Program;Leak{"ml/min"};ResultDescription;LeakMax{"ml/min"};LeakAvg{"ml/min"};LeakMin{"ml/min"};LeakLastPoint{"ml/min"};ScrapArgs{"+","ml/min"};ScrapArgs{"-","ml/min"};Time;"Etalon"','8',NULL),
('59','5','heliummeasuredpoints_exp','DateAndTime DESC, TransactionVer DESC, Pos',NULL,'','get','HeluimPoints;"ID";Version;Point;Phase;Leak{"ml/min"};PressurePart{"ml/min"};ChamberPressure{"ml/min"};AbsolutePreasureChamber{"ml/min"};VacuumPreasureChamber{"ml/min"};Time;Time;"Etalon"','9',NULL),
('60','5','forcepath_exp','DateAndTime DESC, TransactionDetailsId DESC',NULL,'transactiondetailsforcepathwindows_exp;AreaForceMinMax;WindowNum;ForceMinMax;TransactionId','get','ForcePath;"ID";Time;ResultDescription;ProgramId;DmcGenerator;DetailsArg{"ID"}','10',NULL),
('61','5','forcepathdetails_exp','DateAndTime DESC, TransactionDetailsId DESC, PointNum',NULL,'','get','ForcePathArg{Pos};"ID";Point;Force;Path;Time;DetailsArg{"ID"};Time;"Etalon"','11',NULL),
('62','6','transactions','TransactionId','TransactionId>0',NULL,'getAll',NULL,'1',NULL),
('63','6','transactiondetails','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('64','6','transactionslog','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('65','6','transactiondetailslog','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('66','6','leaktestermeasurements','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('67','6','leaktestermeasurementsdetails','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('68','6','leaktestermeasurementslog','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('69','6','leaktestermeasurementsdetailslog','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('70','6','forcepath','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('71','6','forcepathdetails','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('72','6','forcepathwindows','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('73','6','heliummeasurement','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('74','6','heliummeasuredpoints','TransactionId','transactions',NULL,NULL,NULL,'2',NULL),
('75','1','logtransactionlist',NULL,NULL,NULL,'none',NULL,'0',NULL),
('76','1','logerrorlist',NULL,NULL,NULL,'none',NULL,'0',NULL),
('77','1','eventslog',NULL,NULL,NULL,'none',NULL,'0',NULL),
('78','1','logupgrade',NULL,NULL,NULL,'none',NULL,'0',NULL),
('79','1','iotasklogs',NULL,NULL,NULL,'none',NULL,'0',NULL),
('80','1','dimensionsmeasurements','TransactionId IN ({transactionIdArrayStr})','TransactionId=transactions.TransactionId',NULL,'move',NULL,'14',NULL),
('81','1','transactionsevents',NULL,NULL,NULL,'none',NULL,'0',NULL),
('82','1','leaktestermeasurements_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('83','1','leaktestermeasurementslog_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('84','1','heliummeasurement_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('85','1','dimensionsmeasurements_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('86','1','forcepath_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('87','1','forcepathdetails_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('88','1','forcepathwindows_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('89','1','leaktestermeasurementsdetails_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('90','1','leaktestermeasurementsdetailslog_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('91','1','heliummeasuredpoints_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('92','1','transactionslog_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('93','1','transactiondetailslog_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('94','1','transactiondetails_archive',NULL,NULL,NULL,'none',NULL,'0',NULL),
('95','6','leaktestermeasurements_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('96','6','leaktestermeasurementslog_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('97','6','heliummeasurement_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('98','6','dimensionsmeasurements_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('99','6','forcepath_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('100','6','forcepathdetails_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('101','6','forcepathwindows_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('102','6','leaktestermeasurementsdetails_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('103','6','leaktestermeasurementsdetailslog_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('104','6','heliummeasuredpoints_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('105','6','transactionslog_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('106','6','transactiondetailslog_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('107','6','transactiondetails_archive',NULL,NULL,NULL,'none',NULL,'3',NULL),
('108','7','forcepathdetails',NULL,NULL,NULL,NULL,NULL,'1',NULL),
('109','8','transactions',NULL,'1000','0',NULL,NULL,'1',NULL)                                
;
/*!40000 ALTER TABLE `iotaskdetails` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2025-03-13 10:51:28
